<?php
add_action("acf/include_fields", function () {
    if (!function_exists("acf_add_local_field_group")) {
        return;
    }

    acf_add_local_field_group([
        "key" => "group_67bdbd8ba98b7",
        "title" => "Home | Testimonials",
        "fields" => [
            [
                "key" => "field_67bdbd8bea12f",
                "label" => "Testimonial",
                "name" => "testimonial",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "pagination" => 0,
                "min" => 0,
                "max" => 0,
                "collapsed" => "",
                "button_label" => "Add Row",
                "rows_per_page" => 20,
                "sub_fields" => [
                    [
                        "key" => "field_67bdbf04ea131",
                        "label" => "Quote",
                        "name" => "quote",
                        "aria-label" => "",
                        "type" => "textarea",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "allow_in_bindings" => 0,
                        "rows" => 3,
                        "placeholder" => "",
                        "new_lines" => "",
                        "parent_repeater" => "field_67bdbd8bea12f",
                    ],
                    [
                        "key" => "field_67bdbf13ea132",
                        "label" => "Portrait",
                        "name" => "portrait",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "40",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "all",
                        "min_width" => "",
                        "min_height" => "",
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => "",
                        "mime_types" => "",
                        "allow_in_bindings" => 0,
                        "preview_size" => "medium",
                        "parent_repeater" => "field_67bdbd8bea12f",
                    ],
                    [
                        "key" => "field_67bdc35c5bd6e",
                        "label" => "Author",
                        "name" => "author",
                        "aria-label" => "",
                        "type" => "group",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "60",
                            "class" => "",
                            "id" => "",
                        ],
                        "layout" => "block",
                        "sub_fields" => [
                            [
                                "key" => "field_67bdbdb9ea130",
                                "label" => "Name",
                                "name" => "name",
                                "aria-label" => "",
                                "type" => "text",
                                "instructions" => "",
                                "required" => 0,
                                "conditional_logic" => 0,
                                "wrapper" => [
                                    "width" => "",
                                    "class" => "",
                                    "id" => "",
                                ],
                                "default_value" => "",
                                "maxlength" => "",
                                "allow_in_bindings" => 0,
                                "placeholder" => "",
                                "prepend" => "",
                                "append" => "",
                            ],
                            [
                                "key" => "field_67bdc3685bd6f",
                                "label" => "Funktion",
                                "name" => "funktion",
                                "aria-label" => "",
                                "type" => "text",
                                "instructions" => "",
                                "required" => 0,
                                "conditional_logic" => 0,
                                "wrapper" => [
                                    "width" => "",
                                    "class" => "",
                                    "id" => "",
                                ],
                                "default_value" => "",
                                "maxlength" => "",
                                "allow_in_bindings" => 0,
                                "placeholder" => "",
                                "prepend" => "",
                                "append" => "",
                            ],
                        ],
                        "parent_repeater" => "field_67bdbd8bea12f",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "page_type",
                    "operator" => "==",
                    "value" => "front_page",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
    ]);
});
