<?php
add_action("acf/include_fields", function () {
    if (!function_exists("acf_add_local_field_group")) {
        return;
    }

    acf_add_local_field_group([
        "key" => "group_679a4e8aa31c5",
        "title" => "Home | Teaser",
        "fields" => [
            [
                "key" => "field_679a4e8ae0891",
                "label" => "Teasers",
                "name" => "teasers",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "pagination" => 1,
                "rows_per_page" => 3,
                "min" => 0,
                "max" => 0,
                "collapsed" => "field_679a4eb2e0892",
                "button_label" => "Add teaser",
                "sub_fields" => [
                    [
                        "key" => "field_679a4ee8e0895",
                        "label" => "Kategorie",
                        "name" => "kategorie",
                        "aria-label" => "",
                        "type" => "select",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "choices" => [
                            "post" => "Journal Post",
                            "meet" => "Meet",
                            "wiki" => "Wiki",
                        ],
                        "default_value" => false,
                        "return_format" => "value",
                        "multiple" => 0,
                        "allow_null" => 0,
                        "allow_in_bindings" => 0,
                        "ui" => 0,
                        "ajax" => 0,
                        "placeholder" => "",
                        "create_options" => 0,
                        "save_options" => 0,
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                    [
                        "key" => "field_679a4ebde0893",
                        "label" => "Image",
                        "name" => "image",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "all",
                        "min_width" => "",
                        "min_height" => "",
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => "",
                        "mime_types" => "",
                        "allow_in_bindings" => 1,
                        "preview_size" => "medium",
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                    [
                        "key" => "field_679a4eb2e0892",
                        "label" => "Title",
                        "name" => "title",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                    [
                        "key" => "field_679a4ec7e0894",
                        "label" => "Excerpt",
                        "name" => "excerpt",
                        "aria-label" => "",
                        "type" => "textarea",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => 320,
                        "allow_in_bindings" => 0,
                        "rows" => 4,
                        "placeholder" => "",
                        "new_lines" => "",
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                    [
                        "key" => "field_67b724fb74073",
                        "label" => "Datum",
                        "name" => "date",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                    [
                        "key" => "field_67b747dc5153a",
                        "label" => "Link",
                        "name" => "link",
                        "aria-label" => "",
                        "type" => "url",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "parent_repeater" => "field_679a4e8ae0891",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "page_type",
                    "operator" => "==",
                    "value" => "front_page",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
    ]);
});
