<?php
add_action("acf/include_fields", function () {
    if (!function_exists("acf_add_local_field_group")) {
        return;
    }

    acf_add_local_field_group([
        "key" => "group_69723ba461c0e",
        "title" => "Home | Medienpartner",
        "fields" => [
            [
                "key" => "field_69723ba462e4a",
                "label" => "Medienpartner",
                "name" => "medienpartner",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "table",
                "pagination" => 0,
                "min" => 0,
                "max" => 0,
                "collapsed" => "",
                "button_label" => "Add Row",
                "rows_per_page" => 20,
                "sub_fields" => [
                    [
                        "key" => "field_69723ba463c34",
                        "label" => "Logo",
                        "name" => "logo",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "all",
                        "min_width" => "",
                        "min_height" => "",
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => "",
                        "mime_types" => "",
                        "allow_in_bindings" => 0,
                        "preview_size" => "medium",
                        "parent_repeater" => "field_69723ba462e4a",
                    ],
                    [
                        "key" => "field_69723ba463c3e",
                        "label" => "Name",
                        "name" => "name",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_69723ba462e4a",
                    ],
                    [
                        "key" => "field_69723ba463c42",
                        "label" => "Link",
                        "name" => "link",
                        "aria-label" => "",
                        "type" => "url",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "parent_repeater" => "field_69723ba462e4a",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "post",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
        "display_title" => "",
    ]);
});
